import type { CSSProperties } from 'react'
import { categories, type StudyWord } from '../data/words'

type WordSceneProps = {
  word: StudyWord
  compact?: boolean
}

const categoryEmoji: Record<StudyWord['category'], string> = {
  morning: '🌅',
  play: '🎯',
  home: '🏠',
  class: '✏️',
  food: '🍽️',
  body: '🧍',
  feeling: '😊',
  place: '📍',
  nature: '🌿',
}

const wordEmojiGroups: Array<[string, readonly string[]]> = [
  ['🏃', ['run']],
  ['🚶', ['walk', 'leave']],
  ['🤾', ['jump', 'hop', 'skip']],
  ['👶', ['crawl', 'baby']],
  ['🧗', ['climb']],
  ['🛝', ['slide', 'playground']],
  ['🌀', ['swing', 'turn']],
  ['💃', ['dance']],
  ['➡️', ['go', 'right', 'tomorrow']],
  ['⬅️', ['come', 'left', 'yesterday']],
  ['🛑', ['stop']],
  ['🟢', ['start']],
  ['👣', ['follow']],
  ['🚩', ['lead']],
  ['🚸', ['cross']],
  ['↪️', ['pass']],
  ['⏳', ['wait']],
  ['🪑', ['sit', 'chair', 'desk', 'table']],
  ['🧍', ['stand', 'child']],
  ['🙇', ['bend', 'sorry']],
  ['🧘', ['stretch', 'rest']],
  ['🙋', ['reach', 'excuse-me']],
  ['👉', ['point', 'push']],
  ['👆', ['touch']],
  ['🤲', ['hold', 'take']],
  ['📦', ['carry']],
  ['⬇️', ['drop', 'down', 'low', 'under']],
  ['👈', ['pull']],
  ['🚪', ['open', 'close', 'door']],
  ['📥', ['put', 'in']],
  ['🎁', ['give']],
  ['🙌', ['get']],
  ['🧺', ['bring', 'fold', 'tidy']],
  ['✅', ['pick', 'answer', 'choose', 'all']],
  ['⏰', ['wake', 'now']],
  ['🧼', ['wash', 'dirty']],
  ['🪥', ['brush']],
  ['💇', ['comb', 'hair']],
  ['👕', ['dress', 'shirt']],
  ['🧢', ['wear', 'hat']],
  ['🎒', ['pack', 'bag']],
  ['🏁', ['arrive', 'finish', 'last']],
  ['🧽', ['wipe', 'scrub', 'erase']],
  ['🧹', ['clean', 'sweep']],
  ['🪣', ['mop', 'rinse']],
  ['🧥', ['hang', 'coat', 'jacket']],
  ['🗂️', ['sort']],
  ['🍽️', ['eat', 'plate', 'tray']],
  ['🥤', ['drink', 'straw']],
  ['🍎', ['bite', 'apple']],
  ['😋', ['chew', 'taste']],
  ['👅', ['swallow']],
  ['🫗', ['pour']],
  ['🥣', ['mix', 'bowl', 'yogurt']],
  ['🍳', ['cook', 'kitchen']],
  ['🥖', ['bake']],
  ['☕', ['cup']],
  ['🥄', ['spoon']],
  ['🍴', ['fork']],
  ['🧻', ['napkin']],
  ['🍼', ['bottle']],
  ['🍱', ['lunchbox']],
  ['🍚', ['rice']],
  ['🍞', ['bread']],
  ['🥚', ['egg']],
  ['🍲', ['soup']],
  ['🥛', ['milk']],
  ['💧', ['water', 'wet']],
  ['🧃', ['juice']],
  ['🍜', ['noodle']],
  ['🧀', ['cheese']],
  ['🍌', ['banana']],
  ['🍊', ['orange']],
  ['🍇', ['grape']],
  ['🍓', ['strawberry']],
  ['🥕', ['carrot']],
  ['🥔', ['potato']],
  ['🍅', ['tomato']],
  ['🌽', ['corn']],
  ['🥗', ['salad']],
  ['📖', ['read']],
  ['✏️', ['write', 'pencil']],
  ['🎨', ['draw']],
  ['🖍️', ['color', 'crayon']],
  ['🔢', ['count', 'many']],
  ['🔤', ['spell']],
  ['✂️', ['cut', 'scissors']],
  ['🧴', ['glue', 'glue-stick']],
  ['📋', ['copy']],
  ['🎧', ['listen']],
  ['👂', ['hear', 'ear']],
  ['👀', ['look']],
  ['👁️', ['see', 'eye']],
  ['📺', ['watch']],
  ['🗣️', ['say', 'tell']],
  ['❓', ['ask', 'lose']],
  ['🔁', ['repeat']],
  ['📚', ['book', 'library']],
  ['🖊️', ['marker']],
  ['📄', ['paper']],
  ['◻️', ['eraser']],
  ['📏', ['ruler', 'long']],
  ['🏠', ['home']],
  ['🏫', ['school']],
  ['🧑‍🏫', ['classroom', 'teacher']],
  ['🚽', ['bathroom']],
  ['🛏️', ['bedroom', 'bed', 'pajamas']],
  ['🏞️', ['park']],
  ['🏪', ['store']],
  ['🪟', ['window']],
  ['🛋️', ['sofa']],
  ['💡', ['lamp', 'light']],
  ['🕒', ['clock', 'later']],
  ['🪞', ['mirror']],
  ['🗄️', ['shelf']],
  ['👩', ['mom']],
  ['👨', ['dad']],
  ['👦', ['brother']],
  ['👧', ['sister']],
  ['🧒', ['friend']],
  ['👨‍👩‍👧', ['family']],
  ['🏘️', ['neighbor']],
  ['😊', ['happy']],
  ['😢', ['sad']],
  ['😠', ['angry']],
  ['😨', ['scared']],
  ['😴', ['tired']],
  ['🤩', ['excited']],
  ['😐', ['bored']],
  ['😌', ['proud']],
  ['☺️', ['shy']],
  ['😮', ['surprised']],
  ['🙏', ['please', 'thanks']],
  ['👋', ['hello', 'goodbye']],
  ['🤗', ['welcome']],
  ['🤝', ['share', 'promise']],
  ['🆘', ['help']],
  ['🙂', ['head', 'face']],
  ['👃', ['nose']],
  ['👄', ['mouth']],
  ['🦷', ['tooth']],
  ['✋', ['hand']],
  ['🦶', ['foot']],
  ['👖', ['pants']],
  ['👟', ['shoes']],
  ['🧦', ['socks']],
  ['👗', ['skirt']],
  ['🧤', ['gloves']],
  ['☀️', ['sun', 'afternoon']],
  ['🌙', ['moon', 'night']],
  ['⭐', ['star']],
  ['☁️', ['cloud']],
  ['🌧️', ['rain']],
  ['❄️', ['snow', 'cold']],
  ['💨', ['wind']],
  ['🌤️', ['sky']],
  ['🌳', ['tree']],
  ['🌷', ['flower']],
  ['🐶', ['dog']],
  ['🐱', ['cat']],
  ['🐦', ['bird']],
  ['🐟', ['fish']],
  ['🦆', ['duck']],
  ['🐜', ['ant']],
  ['🐝', ['bee']],
  ['🦋', ['butterfly']],
  ['🐸', ['frog']],
  ['🐰', ['rabbit']],
  ['🔵', ['big', 'blue']],
  ['🔹', ['small', 'few']],
  ['↔️', ['short', 'next-to', 'between']],
  ['🏙️', ['tall']],
  ['🫙', ['full', 'empty']],
  ['🏋️', ['heavy']],
  ['🪶', ['soft']],
  ['🔥', ['hot']],
  ['♨️', ['warm']],
  ['🧊', ['cool']],
  ['🧸', ['toy']],
  ['🪨', ['hard']],
  ['🔊', ['loud']],
  ['🤫', ['quiet']],
  ['🔴', ['red']],
  ['🟡', ['yellow']],
  ['🟢', ['green']],
  ['⚫', ['black']],
  ['⚪', ['white']],
  ['⭕', ['circle']],
  ['◼️', ['square']],
  ['🔺', ['triangle']],
  ['➖', ['line', 'less']],
  ['⬆️', ['up', 'on']],
  ['🔼', ['on']],
  ['🔙', ['behind']],
  ['🌅', ['morning-word']],
  ['🌆', ['evening']],
  ['📅', ['today']],
  ['⏱️', ['soon']],
  ['1️⃣', ['one']],
  ['2️⃣', ['two']],
  ['3️⃣', ['three']],
  ['🥇', ['first']],
  ['➕', ['more']],
  ['⚽', ['ball']],
  ['🚲', ['bike']],
  ['🧱', ['block']],
  ['🪆', ['doll']],
  ['🧩', ['puzzle']],
  ['🪁', ['kite']],
  ['🪢', ['rope']],
  ['⚖️', ['seesaw']],
  ['🛴', ['scooter']],
  ['🔎', ['find']],
  ['🛠️', ['make']],
  ['💔', ['break']],
  ['🔧', ['fix']],
  ['🎯', ['try']],
  ['🎹', ['practice']],
  ['🧠', ['remember']],
]

const wordEmoji = Object.fromEntries(
  wordEmojiGroups.flatMap(([emoji, ids]) => ids.map((id) => [id, emoji])),
) as Record<string, string>

const modifierEmoji: Record<string, string> = {
  red: '🔴',
  blue: '🔵',
  yellow: '🟡',
  green: '🟢',
  black: '⚫',
  white: '⚪',
  pink: '🌸',
  purple: '🟣',
  brown: '🟤',
  orange: '🟠',
  big: '↗️',
  small: '↘️',
  fast: '💨',
  slow: '🐌',
  sleepy: '💤',
  hungry: '😋',
  friendly: '🤝',
  wild: '🌿',
  baby: '👶',
  quiet: '🤫',
  ride: '🛞',
  drive: '🛞',
  take: '🤲',
  wait: '⏳',
  board: '⬆️',
  wash: '🧼',
  fix: '🔧',
  park: '🅿️',
  find: '🔎',
  miss: '❗',
  kind: '💛',
  busy: '⏱️',
  helpful: '🆘',
  brave: '🛡️',
  careful: '👀',
  smart: '🧠',
  strong: '💪',
  bright: '✨',
  dark: '🌙',
  round: '⭕',
  tiny: '🔹',
  giant: '🏔️',
  moving: '➡️',
  warm: '♨️',
  cold: '🧊',
  shiny: '💎',
  kick: '🦵',
  throw: '↗️',
  catch: '🙌',
  bounce: '🏀',
  paint: '🎨',
  draw: '✏️',
  play: '▶️',
  sing: '🎵',
  build: '🧱',
  show: '👁️',
  tap: '👆',
  click: '🖱️',
  swipe: '↔️',
  open: '↗️',
  close: '↘️',
  charge: '🔋',
  watch: '👀',
  send: '✉️',
  save: '💾',
  delete: '🗑️',
}

const toneColors = ['#ffcf33', '#8ec9ff', '#f8a6c1', '#a7e2b8', '#d9c4ff', '#ffd7a8']

function hashText(text: string) {
  return Array.from(text).reduce((total, char) => total + char.charCodeAt(0), 0)
}

function getVisual(word: StudyWord) {
  return word.icon ?? wordEmoji[word.id] ?? categoryEmoji[word.category]
}

function getModifierVisual(word: StudyWord) {
  const tokens = word.word.split(/\s+/)
  const modifier = tokens.find((token) => modifierEmoji[token])

  return modifier ? modifierEmoji[modifier] : categoryEmoji[word.category]
}

export function WordScene({ word, compact = false }: WordSceneProps) {
  const category = categories[word.category]
  const emoji = getVisual(word)
  const modifier = getModifierVisual(word)
  const tone = toneColors[hashText(word.id) % toneColors.length]
  const style = {
    '--scene-accent': category.color,
    '--scene-tone': tone,
  } as CSSProperties

  return (
    <div
      className={compact ? 'word-scene word-scene--compact' : 'word-scene'}
      role="img"
      aria-label={`${word.meaning} 그림`}
      style={style}
    >
      <span className="word-scene__grain" aria-hidden="true" />
      <div className="word-picture">
        <span className="word-picture__ring" aria-hidden="true" />
        <span className="word-picture__halo" aria-hidden="true" />
        <span className="word-picture__emoji" aria-hidden="true">
          {emoji}
        </span>
        <span className="word-picture__modifier" aria-hidden="true">
          {modifier}
        </span>
        <span className="word-picture__base" aria-hidden="true" />
      </div>
      <span className="word-picture__glint" aria-hidden="true" />
      <span className="word-picture__chip">{category.shortLabel}</span>
    </div>
  )
}
